version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: backend
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app
    volumes:
      - .:/backend
      - /backend/node_modules
    command: npm run server
    restart: always
  postgres:
    image: postgres:12
    env_file:
      - .env
    expose:
      - "5432"
    networks:
      - app
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - 5432:5432
    restart: always
networks:
  app:
    driver: bridge
